# Generated by Django 3.1.3 on 2020-12-05 19:36

import datetime

import celestia.bleach_models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("internal_name", models.CharField(max_length=128, unique=True)),
                ("priority", models.SmallIntegerField(default=200)),
                ("is_public", models.BooleanField(default=False)),
                ("icon_code", models.TextField(default="<i>*</i>")),
                ("label_is_html", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "feature",
                "verbose_name_plural": "features",
                "db_table": "builds_feature",
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("icon_code", models.TextField(default="<i>*</i>")),
            ],
            options={
                "verbose_name": "platform",
                "verbose_name_plural": "platforms",
            },
        ),
        migrations.CreateModel(
            name="TranslatedFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang_code",
                    models.SlugField(
                        choices=[("en", "English"), ("ru", "Russian")],
                        default="en",
                        max_length=16,
                    ),
                ),
                ("label_code", models.CharField(max_length=2048)),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="builds.feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature translation",
                "verbose_name_plural": "feature translations",
                "db_table": "builds_feature_trans",
                "abstract": False,
            },
            bases=(celestia.bleach_models.BleachMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date and time updated"
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date and time created",
                    ),
                ),
                ("file", models.FileField(default="test.txt", upload_to="")),
                ("has_doomseeker", models.BooleanField(default=False)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("crc32", models.CharField(blank=True, max_length=8)),
                ("checksum_a", models.CharField(blank=True, max_length=144)),
                ("version", models.CharField(max_length=255)),
                (
                    "file_datetime",
                    models.DateTimeField(
                        default=datetime.datetime(1999, 12, 31, 21, 0, tzinfo=utc),
                        verbose_name="date and time file was changed",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="builds.platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "build",
                "verbose_name_plural": "builds",
            },
        ),
        migrations.AddConstraint(
            model_name="translatedfeature",
            constraint=models.UniqueConstraint(
                fields=("base", "lang_code"),
                name="builds_translatedfeature_unique_for_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="build",
            constraint=models.UniqueConstraint(
                fields=("platform", "version", "has_doomseeker"),
                name="builds_build_unique_for_pfm_opt_and_ver",
            ),
        ),
    ]
