# Generated by Django 3.1.3 on 2020-12-05 18:35

from django.conf import settings
from django.db import migrations


def _get_4_models(apps):
    Platform = apps.get_model("builds.Platform")
    Feature = apps.get_model("builds.Feature")
    TranslatedFeature = apps.get_model("builds.TranslatedFeature")
    Build = apps.get_model("builds.Build")
    return Build, Platform, TranslatedFeature, Feature


def create_items(apps, schema_editor):
    # Get models
    Build, Platform, TranslatedFeature, Feature = _get_4_models(apps)

    win = Platform(name="Windows")
    lin = Platform(name="Linux")
    mac = Platform(name="MacOS")
    for obj in (win, mac, lin):
        obj.full_clean()
        obj.save()

    if settings.DEBUG:
        for pfm, flag in (
            (win, False),
            (lin, False),
            (mac, False),
            (win, True),
            (lin, True),
        ):
            obj = Build(platform=pfm, version="1.42.2", has_doomseeker=flag)
            obj.save()

    # Yay! Indian code!
    feat = Feature(
        internal_name="Quake Movement", label_is_html=True, is_public=True, priority=200
    )
    feat.icon_code = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 93 120"><defs><style>.'
        "cls-1{fill:none;stroke:#830808;stroke-linejoin:round;stroke-width:2px;}</style></defs><title>As"
        'set 4</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_3" data-name="Layer 3"><path clas'
        's="cls-1" d="M91.7,39.71C91.7,62.06,74.39,80.51,52,83.2h0V96L46.35,120.2,40.68,96V83.21h0C18.31'
        ",80.51,1,62.06,1,39.71A43.66,43.66,0,0,1,25,1h0A39.31,39.31,0,0,0,40.68,72.93V59.38a6,6,0,0,0-6-"
        "5.69h-.38V51.23H58.44v2.46h-.38a6,6,0,0,0-6,5.86V72.93A39.31,39.31,0,0,0,67.65,1h0A43.65,43.65,0"
        ',0,1,91.7,39.71Z"/></g></g></svg>'
    )
    feat.full_clean()
    feat.save()
    obj = TranslatedFeature(
        base=feat,
        label_code="<p>Quake Movement</p><p>(configurable)</p>",
        lang_code="en",
    )
    obj.full_clean()
    obj.save()

    feat = Feature(
        internal_name="Improved Netcode",
        label_is_html=True,
        is_public=True,
        priority=400,
    )
    feat.icon_code = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 214 '
        '160"><defs><style>.cls-1{fill:#830808;}.cls-2,.cls-3,.cls-4,.cls-5{fill:none;stroke:#830808;'
        "stroke-miterlimit:10;stroke-width:2px;}.cls-3{stroke-dasharray:4.15 "
        "3.63;}.cls-4{stroke-dasharray:4.99 4.99;}.cls-5{stroke-dasharray:4.92 "
        '4.92;}</style></defs><title>Asset 5</title><g id="Layer_2" data-name="Layer '
        '2"><g id="Layer_3" data-name="Layer 3"><path class="cls-1" '
        'd="M46.58,99.37A3.63,3.63,0,0,1,50.21,103v29.67a3.63,3.63,0,0,1-3.63,3.63H30.46V149h-8.'
        "7V136.3H5.63A3.64,3.64,0,0,1,2,132.67V103a3.64,3.64,0,0,1,3.63-3.63H46.58m0-2H5.63A5.65,5.65,0,"
        "0,0,0,103v29.67a5.64,5.64,0,0,0,5.63,5.63H19.76v9.88H5.49a1.26,1.26,0,0,0-1.26,1.25v.31A1.27,1.27"
        ",0,0,0,5.49,151H46.73A1.26,1.26,0,0,0,48,149.74v-.31a1.25,1.25,0,0,0-1.25-1.25H32.46V138.3H46.58a5."
        '64,5.64,0,0,0,5.63-5.63V103a5.65,5.65,0,0,0-5.63-5.63Z"/><path '
        'class="cls-1" '
        'd="M125.61,99.37a3.64,3.64,0,0,1,3.63,3.63v29.67a3.64,3.64,0,0,1-3.63,3.63H109.49V149h-8.'
        "7V136.3H84.66A3.64,3.64,0,0,1,81,132.67V103a3.64,3.64,0,0,1,3.63-3.63h41m0-2H84.66A5.65,5."
        "65,0,0,0,79,103v29.67a5.64,5.64,0,0,0,5.63,5.63H98.79v9.88H84.52a1.26,1.26,0,0,0-1.26,1.25v."
        "31A1.27,1.27,0,0,0,84.52,151h41.23a1.27,1.27,0,0,0,1.26-1.26v-.31a1.26,1.26,0,0,0-1.26-1.25H111."
        '49V138.3h14.12a5.64,5.64,0,0,0,5.63-5.63V103a5.65,5.65,0,0,0-5.63-5.63Z"/><path '
        'class="cls-1" '
        'd="M125.61,2a3.64,3.64,0,0,1,3.63,3.63V35.29a3.64,3.64,0,0,1-3.63,3.64H109.49v12.7h-8.7V38.'
        "93H84.66A3.64,3.64,0,0,1,81,35.29V5.63A3.64,3.64,0,0,1,84.66,2h41m0-2H84.66A5.64,5.64,0,0,0"
        ",79,5.63V35.29a5.65,5.65,0,0,0,5.63,5.64H98.79V50.8H84.52a1.27,1.27,0,0,0-1.26,1.26v.31a1.27"
        ",1.27,0,0,0,1.26,1.26h41.23A1.27,1.27,0,0,0,127,52.37v-.31a1.27,1.27,0,0,0-1.26-1.26H111.49V4"
        '0.93h14.12a5.65,5.65,0,0,0,5.63-5.64V5.63A5.64,5.64,0,0,0,125.61,0Z"/><path '
        'class="cls-1" '
        'd="M206.05,99.37a3.64,3.64,0,0,1,3.63,3.63v29.67a3.64,3.64,0,0,1-3.63,3.63H189.93V149h-8.71'
        "V136.3H165.1a3.64,3.64,0,0,1-3.63-3.63V103a3.64,3.64,0,0,1,3.63-3.63h41m0-2h-41a5.65,5.65,0"
        ",0,0-5.63,5.63v29.67a5.64,5.64,0,0,0,5.63,5.63h14.12v9.88H165a1.26,1.26,0,0,0-1.26,1.25v.31A"
        "1.27,1.27,0,0,0,165,151h41.23a1.27,1.27,0,0,0,1.26-1.26v-.31a1.26,1.26,0,0,0-1.26-1.25H191.9"
        '3V138.3h14.12a5.64,5.64,0,0,0,5.63-5.63V103a5.65,5.65,0,0,0-5.63-5.63Z"/><line '
        'class="cls-2" x1="105.84" y1="98.79" x2="105.84" y2="96.79"/><line '
        'class="cls-3" x1="105.84" y1="93.15" x2="105.84" y2="56.03"/><line '
        'class="cls-2" x1="105.84" y1="54.21" x2="105.84" y2="52.21"/><line '
        'class="cls-2" x1="179.22" y1="98.79" x2="177.19" y2="97.33"/><line '
        'class="cls-4" x1="173.14" y1="94.42" x2="118.37" y2="55.13"/><line '
        'class="cls-2" x1="116.34" y1="53.67" x2="114.31" y2="52.21"/><line '
        'class="cls-2" x1="32.46" y1="98.79" x2="34.47" y2="97.31"/><line '
        'class="cls-5" x1="38.44" y1="94.4" x2="91.96" y2="55.15"/><line '
        'class="cls-2" x1="93.95" y1="53.69" x2="95.96" y2="52.21"/></g></g></svg>'
    )
    feat.full_clean()
    feat.save()
    obj = TranslatedFeature(
        base=feat, label_code="<p>Improved Netcode</p>", lang_code="en"
    )
    obj.full_clean()
    obj.save()

    feat = Feature(
        internal_name="Tweaks and Fixes",
        label_is_html=True,
        is_public=True,
        priority=600,
    )
    feat.icon_code = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 103.48 '
        '103.48"><defs><style>.cls-1{fill:none;stroke:#830808;stroke-miterlimit:10;stroke-width:2px;}'
        "</style></defs><title>Asset "
        '3</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_3" '
        'data-name="Layer 3"><polyline class="cls-1" points="103.1 45.91 91.58 50.7 '
        '80.51 45.59"/><polyline class="cls-1" points="45.91 103.1 50.7 91.58 45.42 '
        '80.68"/><path class="cls-1" '
        'd="M92.21,87.48a7.6,7.6,0,0,1-10.74,0L66.25,72.26a38,38,0,0,1-8.54,5.18,38.72,3'
        "8.72,0,0,1-31.52-.15A38.76,38.76,0,0,1,26,45.77a38,38,0,0,1,5.18-8.54L26.8,32.8A14.7"
        "7,14.77,0,0,1,8.65,15.9L19.59,23l6.26-9.57-11-7.18A14.77,14.77,0,0,1,37.53,22.07l5.36,"
        "5.36a38.8,38.8,0,0,1,21.33-4.6c.18-.2.37-.41.56-.6a11.69,11.69,0,0,1,13.53-2.15,11.73,11"
        ".73,0,0,1,5.09,5.09A11.7,11.7,0,0,1,81.26,38.7l-.61.56a37.54,37.54,0,0,1-.06,6.36,38.48,38."
        '48,0,0,1-4.54,15L92.2,76.74A7.6,7.6,0,0,1,92.21,87.48Z"/><polyline '
        'class="cls-1" points="57.57 0.38 52.78 11.9 57.89 22.97"/><polyline '
        'class="cls-1" points="0.38 57.57 11.9 52.78 22.8 58.06"/><line class="cls-1" '
        'x1="77.35" y1="1.24" x2="73.5" y2="18.83"/><line class="cls-1" x1="102.31" '
        'y1="26.2" x2="84.72" y2="30.05"/></g></g></svg>'
    )
    feat.full_clean()
    feat.save()
    obj = TranslatedFeature(
        base=feat, label_code="<p>Multiple tweaks and bug fixes</p>", lang_code="en"
    )
    obj.full_clean()
    obj.save()


def remove_items(apps, schema_editor):
    """ Data migration reverse """
    for ModelClass in _get_4_models(apps):
        ModelClass.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_items, remove_items)]
