# Generated by Django 3.1.3 on 2020-12-11 14:49

import builds.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0002_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="priority",
            field=models.SmallIntegerField(
                default=200, help_text="priority of item when ordering"
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="checksum_a",
            field=models.CharField(
                blank=True,
                help_text="filled automatically by file upload,"
                          " supposed to use format '<method>|<hexdigest>'",
                max_length=144,
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="crc32",
            field=models.CharField(
                blank=True, help_text="filled automatically", max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="file",
            field=models.FileField(
                default="test.txt", upload_to=builds.models.Build.make_filename
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="size",
            field=models.PositiveBigIntegerField(default=0, help_text="size in bytes"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon_code",
            field=models.TextField(
                default="<i></i>", help_text="not escaped and may contain html"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="internal_name",
            field=models.CharField(
                help_text="name of feature for internal use. Must be unique.",
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="show this feature on the site"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="label_is_html",
            field=models.BooleanField(
                default=False,
                help_text="label requires marking as safe (disable escaping)"
                          ". label itself is stored in translation table",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="priority",
            field=models.SmallIntegerField(
                default=200, help_text="priority of item when ordering"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="icon_code",
            field=models.TextField(
                blank=True, default="", help_text="not escaped and may contain html"
            ),
        ),
        migrations.AlterField(
            model_name="translatedfeature",
            name="base",
            field=models.ForeignKey(
                help_text="a base model of this translation model",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="builds.feature",
            ),
        ),
        migrations.AlterField(
            model_name="translatedfeature",
            name="label_code",
            field=models.CharField(
                help_text='may contain html, not escaped if base feature has "label_is_html" checked',
                max_length=2048,
            ),
        ),
    ]
