# Generated by Django 3.1.7 on 2021-03-16 05:07

from django.db import migrations, models

import builds.models
import builds.storage


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_add_priority_and_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='file',
            field=models.FileField(storage=builds.storage.BuildOverwriteStorage(),
                                   upload_to=builds.models.Build.make_filename),
        ),
    ]
