# Generated by Django 3.1.7 on 2021-03-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
        ('builds', '0004_auto_20210316_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUploadItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chunked_upload.chunkedupload',),
        ),
    ]
