# Generated by Django 3.2.16 on 2022-12-04 12:32

import datetime

import celestia.abstract_models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc

import builds.models
import builds.storage


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_chunkeduploaditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCDEBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='date and time updated')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time created')),
                ('size', models.PositiveBigIntegerField(default=0, help_text='size in bytes')),
                ('crc32', models.CharField(blank=True, help_text='filled automatically', max_length=8)),
                ('checksum_a', models.CharField(blank=True, help_text="filled automatically by file upload, supposed to use format '<method>|<hexdigest>'", max_length=144)),
                ('version', models.CharField(max_length=255)),
                ('file_datetime', models.DateTimeField(default=datetime.datetime(1999, 12, 31, 21, 0, tzinfo=utc), verbose_name='date and time file was changed')),
                ('file', models.FileField(storage=builds.storage.BuildOverwriteStorage(), upload_to=builds.models.QCDEBuild.make_filename)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='builds.platform')),
            ],
            options={
                'verbose_name': 'QCDE build',
                'verbose_name_plural': 'QCDE builds',
            },
            bases=(celestia.abstract_models.FileProcessingMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='qcdebuild',
            constraint=models.UniqueConstraint(fields=('platform', 'version'), name='builds_qcdebuild_unique_for_pfm_and_ver'),
        ),
    ]
