# Generated by Django 3.2.17 on 2023-03-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_auto_20221204_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDownloadCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='download_counters', to='builds.build')),
                ('qcde_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='download_counters', to='builds.qcdebuild')),
            ],
        ),
        migrations.AddConstraint(
            model_name='weeklydownloadcounter',
            constraint=models.CheckConstraint(check=models.Q(('build__isnull', False), ('qcde_build__isnull', False), _connector='OR'), name='both_builds_not_null'),
        ),
    ]
