# Generated by Django 4.2.19 on 2025-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_auto_20230421_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='checksum_a',
            field=models.CharField(blank=True, help_text="filled automatically by file upload, supposed to use format '&lt;method&gt;|&lt;hexdigest&gt;'", max_length=144),
        ),
        migrations.AlterField(
            model_name='qcdebuild',
            name='checksum_a',
            field=models.CharField(blank=True, help_text="filled automatically by file upload, supposed to use format '&lt;method&gt;|&lt;hexdigest&gt;'", max_length=144),
        ),
    ]
