# Generated by Django 3.1.3 on 2020-12-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageconfig",
            name="page_name",
            field=models.SlugField(
                help_text="page id for internal use, must contain only a-zA-Z0-9-_",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="translatedpageconfig",
            name="base",
            field=models.ForeignKey(
                help_text="a base model of this translation model",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="core.pageconfig",
            ),
        ),
        migrations.AlterField(
            model_name="translatedpageconfig",
            name="meta_descr",
            field=models.TextField(
                blank=True, help_text="Page description (mostly for search engines)"
            ),
        ),
        migrations.AlterField(
            model_name="translatedpageconfig",
            name="meta_keywords",
            field=models.TextField(
                blank=True, help_text="Keywords for search engines", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="translatedpageconfig",
            name="meta_title",
            field=models.CharField(
                help_text="Page title (shown on the browser tab)", max_length=256
            ),
        ),
    ]
