# Generated by Django 3.2.16 on 2022-12-27 03:23

import django.db.models.deletion
from django.db import migrations, models

import bootslider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codename', models.SlugField(max_length=64, unique=True)),
                ('slide_select', models.CharField(default='#slide-', max_length=128)),
                ('animation_class', models.CharField(default='active', max_length=256)),
                ('ride_class', models.CharField(default='carousel', max_length=256)),
                ('inline_style', models.TextField(blank=True, default='')),
                ('interval_ms', models.PositiveIntegerField(default=5000)),
                ('extra_data', models.JSONField(default=bootslider.models.AbstractSlider._default_attrs)),
                ('extra_attrs', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_alt', models.CharField(default='img', max_length=256)),
                ('img', models.ImageField(upload_to=bootslider.models.AbstractSliderImage.make_filename)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='bootslider.slider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
