# Generated by Django 3.2.16 on 2022-12-27 04:30

from django.db import migrations, models

import bootslider.models


class Migration(migrations.Migration):

    dependencies = [
        ('bootslider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='codename',
            field=models.SlugField(help_text='Unique identificator and used as html ID', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='extra_data',
            field=models.JSONField(blank=True, default=bootslider.models.AbstractSlider._default_attrs, help_text='html attributes in JSON format'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='inline_style',
            field=models.TextField(blank=True, default='', help_text='added with slider.media, for container style use extra_attrs'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='interval_ms',
            field=models.PositiveIntegerField(default=5000, help_text='Slide delay in ms'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ride_class',
            field=models.CharField(default='carousel', help_text='class used to init Slider, used in html', max_length=256),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide_select',
            field=models.CharField(default='slide-', max_length=128),
        ),
    ]
