# Generated by Django 3.2.16 on 2023-01-01 17:28

from django.db import migrations, models

import bootslider.models


class Migration(migrations.Migration):

    dependencies = [
        ('bootslider', '0002_auto_20221227_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='crc32',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='preview',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='extra_attrs',
            field=models.JSONField(blank=True, default=dict, help_text='html attributes in JSON format'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='extra_data',
            field=models.JSONField(blank=True, default=bootslider.models.AbstractSlider._default_attrs, help_text='html data-* attributes in JSON format'),
        ),
    ]
